### ISSUE TITLE
Wishlist: support {{#Surface class="{{type}}-header"}}

### ISSUE THREAD

**Issue by arboleya** [gadicc/meteor-famous-views#149]
I can't get to evaluate a variable and set it as a class attribute for a Surface.

Shouldn't this work fine?

``` html
<template name='main'>
  {{> header type='testing'}}
</template>

<template name='header'>
  {{#Surface size='[undefined,30]' class="{{type}}-header"}}
    Hello World
  {{/Surface}}
</template>
```

``` css
.testing-header {
  background-color: hotpink;
}
```
